export const adultTeethMapping = {
  11: [
    '11_Distal',
    '11_Facial',
    '11_Mesial',
    '11_Palatal',
    '11_Uniradicular_Root',
  ],
  12: [
    '12_Distal',
    '12_Facial',
    '12_Mesial',
    '12_Palatal',
    '12_Uniradicular_Root',
  ],
  13: [
    '13_Distal',
    '13_Facial',
    '13_Mesial',
    '13_Palatal',
    '13_Uniradicular_Root',
  ],
  14: [
    '14_Distal',
    '14_Distal_Root',
    '14_Facial',
    '14_Mesial',
    '14_Mesial_Root',
    '14_Occlusal_Facial',
    '14_Occlusal_Palatal',
    '14_Palatal',
  ],
  15: [
    '15_Distal',
    '15_Facial',
    '15_Mesial',
    '15_Occlusal_DistoPalatal',
    '15_Occlusal_Facial',
    '15_Occlusal_MesioPalatal',
    '15_Palatal',
    '15_Uniradicular_Root',
  ],
  16: [
    '16_Distal',
    '16_DistoFacial_Root',
    '16_Facial',
    '16_Mesial',
    '16_MesioFacial_Root',
    '16_Occlusal_DistoFacial',
    '16_Occlusal_MesioFacial',
    '16_Occlusal_Palatal',
    '16_Palatal',
    '16_Palatal_Root',
  ],
  17: [
    '17_Distal',
    '17_DistoFacial_Root',
    '17_Facial',
    '17_Mesial',
    '17_MesioFacial_Root',
    '17_Occlusal_DistoFacial',
    '17_Occlusal_MesioFacial',
    '17_Occlusal_Palatal',
    '17_Palatal',
    '17_Palatal_Root',
  ],
  18: [
    '18_Distal',
    '18_DistoFacial_Root',
    '18_Facial',
    '18_Mesial',
    '18_MesioFacial_Root',
    '18_Occlusal_DistoFacial',
    '18_Occlusal_MesioFacial',
    '18_Occlusal_Palatal',
    '18_Palatal',
    '18_Palatal_Root',
  ],
  21: [
    '21_Distal',
    '21_Facial',
    '21_Mesial',
    '21_Palatal',
    '21_Uniradicular_Root',
  ],
  22: [
    '22_Distal',
    '22_Facial',
    '22_Mesial',
    '22_Palatal',
    '22_Uniradicular_Root',
  ],
  23: [
    '23_Distal',
    '23_Facial',
    '23_Mesial',
    '23_Palatal',
    '23_Uniradicular_Root',
  ],
  24: [
    '24_Distal',
    '24_Distal_Root',
    '24_Facial',
    '24_Mesial',
    '24_Mesial_Root',
    '24_Occlusal_Facial',
    '24_Occlusal_Palatal',
    '24_Palatal',
  ],
  25: [
    '25_Distal',
    '25_Facial',
    '25_Mesial',
    '25_Occlusal_DistoPalatal',
    '25_Occlusal_Facial',
    '25_Occlusal_MesioPalatal',
    '25_Palatal',
    '25_Uniradicular_Root',
  ],
  26: [
    '26_Distal',
    '26_DistoFacial_Root',
    '26_Facial',
    '26_Mesial',
    '26_MesioFacial_Root',
    '26_Occlusal_DistoFacial',
    '26_Occlusal_MesioFacial',
    '26_Occlusal_Palatal',
    '26_Palatal',
    '26_Palatal_Root',
  ],
  27: [
    '27_Distal',
    '27_DistoFacial_Root',
    '27_Facial',
    '27_Mesial',
    '27_MesioFacial_Root',
    '27_Occlusal_DistoFacial',
    '27_Occlusal_MesioFacial',
    '27_Occlusal_Palatal',
    '27_Palatal',
    '27_Palatal_Root',
  ],
  28: [
    '28_Distal',
    '28_DistoFacial_Root',
    '28_Facial',
    '28_Mesial',
    '28_MesioFacial_Root',
    '28_Occlusal_DistoFacial',
    '28_Occlusal_MesioFacial',
    '28_Occlusal_Palatal',
    '28_Palatal',
    '28_Palatal_Root',
  ],
  31: [
    '31_Distal',
    '31_Facial',
    '31_Lingual',
    '31_Mesial',
    '31_Uniradicular_Root',
  ],
  32: [
    '32_Distal',
    '32_Facial',
    '32_Lingual',
    '32_Mesial',
    '32_Uniradicular_Root',
  ],
  33: [
    '33_Distal',
    '33_Facial',
    '33_Lingual',
    '33_Mesial',
    '33_Uniradicular_Root',
  ],
  34: [
    '34_Distal',
    '34_Facial',
    '34_Lingual',
    '34_Mesial',
    '34_Occlusal_Facial',
    '34_Occlusal_Lingual',
    '34_Uniradicular_Root',
  ],
  35: [
    '35_Distal',
    '35_Facial',
    '35_Lingual',
    '35_Mesial',
    '35_Occlusal_DistoLingual',
    '35_Occlusal_Facial',
    '35_Occlusal_MesioLingual',
    '35_Uniradicular_Root',
  ],
  36: [
    '36_Distal',
    '36_Distal_Root',
    '36_Facial',
    '36_Lingual',
    '36_Mesial',
    '36_Mesial_Root',
    '36_Occlusal_DistoLingual',
    '36_Occlusal_Facial',
    '36_Occlusal_MesioLingual',
  ],
  37: [
    '37_Distal',
    '37_Distal_Root',
    '37_Facial',
    '37_Lingual',
    '37_Mesial',
    '37_Mesial_Root',
    '37_Occlusal_DistoLingual',
    '37_Occlusal_Facial',
    '37_Occlusal_MesioLingual',
  ],
  38: [
    '38_Distal',
    '38_Distal_Root',
    '38_Facial',
    '38_Lingual',
    '38_Mesial',
    '38_Mesial_Root',
    '38_Occlusal_DistoLingual',
    '38_Occlusal_Facial',
    '38_Occlusal_MesioLingual',
  ],
  41: [
    '41_Distal',
    '41_Facial',
    '41_Lingual',
    '41_Mesial',
    '41_Uniradicular_Root',
  ],
  42: [
    '42_Distal',
    '42_Facial',
    '42_Lingual',
    '42_Mesial',
    '42_Uniradicular_Root',
  ],
  43: [
    '43_Distal',
    '43_Facial',
    '43_Lingual',
    '43_Mesial',
    '43_Uniradicular_Root',
  ],
  44: [
    '44_Distal',
    '44_Facial',
    '44_Lingual',
    '44_Mesial',
    '44_Occlusal_Facial',
    '44_Occlusal_Lingual',
    '44_Uniradicular_Root',
  ],
  45: [
    '45_Distal',
    '45_Facial',
    '45_Lingual',
    '45_Mesial',
    '45_Occlusal_DistoLingual',
    '45_Occlusal_Facial',
    '45_Occlusal_MesioLingual',
    '45_Uniradicular_Root',
  ],
  46: [
    '46_Distal',
    '46_Distal_Root',
    '46_Facial',
    '46_Lingual',
    '46_Mesial',
    '46_Mesial_Root',
    '46_Occlusal_DistoLingual',
    '46_Occlusal_Facial',
    '46_Occlusal_MesioLingual',
  ],
  47: [
    '47_Distal',
    '47_Distal_Root',
    '47_Facial',
    '47_Lingual',
    '47_Mesial',
    '47_Mesial_Root',
    '47_Occlusal_DistoLingual',
    '47_Occlusal_Facial',
    '47_Occlusal_MesioLingual',
  ],
  48: [
    '48_Distal',
    '48_Distal_Root',
    '48_Facial',
    '48_Lingual',
    '48_Mesial',
    '48_Mesial_Root',
    '48_Occlusal_DistoLingual',
    '48_Occlusal_Facial',
    '48_Occlusal_MesioLingual',
  ],
};

export const childTeethMapping = {
  51: [
    '51_Distal',
    '51_Facial',
    '51_Mesial',
    '51_Palatal',
    '51_Uniradicular_Root',
  ],
  52: [
    '52_Distal',
    '52_Facial',
    '52_Mesial',
    '52_Palatal',
    '52_Uniradicular_Root',
  ],
  53: [
    '53_Distal',
    '53_Facial',
    '53_Mesial',
    '53_Palatal',
    '53_Uniradicular_Root',
  ],
  54: [
    '54_Distal',
    '54_DistoFacial_Root',
    '54_Facial',
    '54_Mesial',
    '54_MesioFacial_Root',
    '54_Occlusal_DistoFacial',
    '54_Occlusal_MesioFacial',
    '54_Occlusal_Palatal',
    '54_Palatal',
    '54_Palatal_Root',
  ],
  55: [
    '55_Distal',
    '55_DistoFacial_Root',
    '55_Facial',
    '55_Mesial',
    '55_MesioFacial_Root',
    '55_Occlusal_DistoFacial',
    '55_Occlusal_MesioFacial',
    '55_Occlusal_Palatal',
    '55_Palatal',
    '55_Palatal_Root',
  ],
  61: [
    '61_Distal',
    '61_Facial',
    '61_Mesial',
    '61_Palatal',
    '61_Uniradicular_Root',
  ],
  62: [
    '62_Distal',
    '62_Facial',
    '62_Mesial',
    '62_Palatal',
    '62_Uniradicular_Root',
  ],
  63: [
    '63_Distal',
    '63_Facial',
    '63_Mesial',
    '63_Palatal',
    '63_Uniradicular_Root',
  ],
  64: [
    '64_Distal',
    '64_DistoFacial_Root',
    '64_Facial',
    '64_Mesial',
    '64_MesioFacial_Root',
    '64_Occlusal_DistoFacial',
    '64_Occlusal_MesioFacial',
    '64_Occlusal_Palatal',
    '64_Palatal',
    '64_Palatal_Root',
  ],
  65: [
    '65_Distal',
    '65_DistoFacial_Root',
    '65_Facial',
    '65_Mesial',
    '65_MesioFacial_Root',
    '65_Occlusal_DistoFacial',
    '65_Occlusal_MesioFacial',
    '65_Occlusal_Palatal',
    '65_Palatal',
    '65_Palatal_Root',
  ],
  71: [
    '71_Distal',
    '71_Facial',
    '71_Lingual',
    '71_Mesial',
    '71_Uniradicular_Root',
  ],
  72: [
    '72_Distal',
    '72_Facial',
    '72_Lingual',
    '72_Mesial',
    '72_Uniradicular_Root',
  ],
  73: [
    '73_Distal',
    '73_Facial',
    '73_Lingual',
    '73_Mesial',
    '73_Uniradicular_Root',
  ],
  74: [
    '74_Distal',
    '74_Distal_Root',
    '74_Facial',
    '74_Lingual',
    '74_Mesial',
    '74_Mesial_Root',
    '74_Occlusal_DistoLingual',
    '74_Occlusal_Facial',
    '74_Occlusal_MesioLingual',
  ],
  75: [
    '75_Distal',
    '75_Distal_Root',
    '75_Facial',
    '75_Lingual',
    '75_Mesial',
    '75_Mesial_Root',
    '75_Occlusal_DistoLingual',
    '75_Occlusal_Facial',
    '75_Occlusal_MesioLingual',
  ],
  81: [
    '81_Distal',
    '81_Facial',
    '81_Lingual',
    '81_Mesial',
    '81_Uniradicular_Root',
  ],
  82: [
    '82_Distal',
    '82_Facial',
    '82_Lingual',
    '82_Mesial',
    '82_Uniradicular_Root',
  ],
  83: [
    '83_Distal',
    '83_Facial',
    '83_Lingual',
    '83_Mesial',
    '83_Uniradicular_Root',
  ],
  84: [
    '84_Distal',
    '84_Distal_Root',
    '84_Facial',
    '84_Lingual',
    '84_Mesial',
    '84_Mesial_Root',
    '84_Occlusal_DistoLingual',
    '84_Occlusal_Facial',
    '84_Occlusal_MesioLingual',
  ],
  85: [
    '85_Distal',
    '85_Distal_Root',
    '85_Facial',
    '85_Lingual',
    '85_Mesial',
    '85_Mesial_Root',
    '85_Occlusal_DistoLingual',
    '85_Occlusal_Facial',
    '85_Occlusal_MesioLingual',
  ],
};
